#!/usr/bin/env ruby
# frozen_string_literal: true

# scout cortex property_remove -- Remove a property definition (history is kept)

require 'scout'

require_relative '../../../lib/Cortex/cli'

$0 = "scout #{$previous_commands.any? ? "#{$previous_commands * ' '} " : ''}#{File.basename(__FILE__)}" if $previous_commands
cmd = $0

options = SOPT.setup <<~EOF

  Remove a property definition (history is kept)

  $ #{cmd} [<options>] <entity_type> <property>

  -h--help Print this help
  -et--entity_type* Entity type (Ruby constant path, e.g. Gene)
  -p--property* Property name (snake_case)
  -e--expected_version* Version being removed (optimistic concurrency)
  -a--agent* Agent name recorded in provenance
EOF
if options[:help]
  if defined? scout_usage
    scout_usage
  else
    puts SOPT.doc
  end
  exit 0
end

entity_type, property, expected_version = IndiferentHash.process_options options, :entity_type, :property, :expected_version

entity_type = ARGV.shift if entity_type.nil?
property = ARGV.shift if property.nil?

raise MissingParameterException, :entity_type if entity_type.nil?
raise MissingParameterException, :property if property.nil?
raise MissingParameterException, :expected_version if expected_version.nil?

options[:entity_type] = entity_type
options[:property] = property
options[:expected_version] = expected_version

raise ParameterException, "Extra positional arguments: #{ARGV * ' '}" unless ARGV.empty?

Cortex::CLI.dispatch 'cortex_property_remove', options
