#!/usr/bin/env ruby
# frozen_string_literal: true

# scout cortex rename -- Rename a workspace resource in place

require 'scout'

require_relative '../../../lib/Cortex/cli'

$0 = "scout #{$previous_commands.any? ? "#{$previous_commands * ' '} " : ''}#{File.basename(__FILE__)}" if $previous_commands
cmd = $0

options = SOPT.setup <<~EOF

  Rename a workspace resource in place

  $ #{cmd} [<options>] <name> <new_name>

  -h--help Print this help
  -t--type* Namespace of the resource to rename
  -n--name* Current logical name
  -ne--new_name* New logical name
  -a--agent* Optional agent name recorded in the .meta version entry
EOF
if options[:help]
  if defined? scout_usage
    scout_usage
  else
    puts SOPT.doc
  end
  exit 0
end

name, new_name, type = IndiferentHash.process_options options, :name, :new_name, :type

name = ARGV.shift if name.nil?
new_name = ARGV.shift if new_name.nil?

raise MissingParameterException, :type if type.nil?
raise MissingParameterException, :name if name.nil?
raise MissingParameterException, :new_name if new_name.nil?

options[:name] = name
options[:new_name] = new_name
options[:type] = type

raise ParameterException, "Extra positional arguments: #{ARGV * ' '}" unless ARGV.empty?

Cortex::CLI.dispatch 'cortex_rename', options
